# Generated by Django 2.0.7 on 2020-06-04 13:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='properties',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sapId', models.PositiveIntegerField()),
                ('macAddress', models.GenericIPAddressField()),
            ],
        ),
        migrations.CreateModel(
            name='router',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostName', models.CharField(max_length=256)),
            ],
        ),
        migrations.AddField(
            model_name='properties',
            name='hostName',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='routers', to='manage_router.router'),
        ),
    ]
