# Generated by Django 2.0.7 on 2020-06-04 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage_router', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='properties',
            name='macAddress',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='properties',
            name='sapId',
            field=models.CharField(max_length=256),
        ),
    ]
