# Generated by Django 2.0.7 on 2020-06-04 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage_router', '0002_auto_20200604_1921'),
    ]

    operations = [
        migrations.AddField(
            model_name='properties',
            name='loopBack',
            field=models.CharField(default='ipv4', max_length=256),
            preserve_default=False,
        ),
    ]
