# Generated by Django 2.0.7 on 2020-06-04 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage_router', '0003_properties_loopback'),
    ]

    operations = [
        migrations.AlterField(
            model_name='properties',
            name='loopBack',
            field=models.CharField(max_length=4),
        ),
        migrations.AlterField(
            model_name='properties',
            name='macAddress',
            field=models.CharField(max_length=17),
        ),
        migrations.AlterField(
            model_name='properties',
            name='sapId',
            field=models.CharField(max_length=18),
        ),
        migrations.AlterField(
            model_name='router',
            name='hostName',
            field=models.CharField(max_length=14),
        ),
    ]
