# Generated by Django 2.0.7 on 2020-06-04 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage_router', '0004_auto_20200604_1928'),
    ]

    operations = [
        migrations.AlterField(
            model_name='properties',
            name='loopBack',
            field=models.CharField(default='ipv4', max_length=4),
        ),
    ]
